# Generated by Django 3.2.5 on 2021-07-27 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_usermoreinfo_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usermoreinfo',
            name='is_active',
            field=models.IntegerField(null=True),
        ),
    ]
