# Generated by Django 3.2.5 on 2021-07-10 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Users',
        ),
        migrations.RenameModel(
            old_name='UserType',
            new_name='UsersType',
        ),
    ]
